### ISSUE TITLE
Instructions

### ISSUE THREAD

**Issue by TonyNolan** [mlhubber/mlhub#118]
Good Morning,

In the instruction sequence promoting the next step. If you choose not to replace a file you have already loaded.  Then it just stops.

The only way to get the next command in the sequence, is to replace the exact same file.

Could the next step be shown if you choose yes or no please.

**Comment by mlhubber** [comment]
Thanks for the suggestion. The next step after an _install_ is usually a _configure_. Perhaps that should be suggested after the aborted install (over the already installed package). It may also be possible to track for a package whether it has already been configured, and if so to then suggest _readme_ as the next command (the default after a _configure_).

**Comment by gjwgit** [comment]
MLHub version 3.5.11 from pypi and commit 5c46c51d2ddb2c24bdeed7d06f56d7ddd21a4cef implements the next step as _configure_ here. Generally a _configure_ will do nothing if it is already configured, so it seems reasonable to suggest _configure_ here rather than checking if it has already been configured. Closing this issue now but re-open if you think we should track if a _configure_ has already been done and so should suggest _readme_. Thanks
