### ISSUE TITLE
Support git lfs stored files

### ISSUE THREAD

**Issue by gjwgit** [mlhubber/mlhub#197]
Large files on git may be stored as git lfs. The actual file in the repository is something like:

```
version https://git-lfs.github.com/spec/v1
oid sha256:52d8af56969cbc326fa9b90b97f1f0e9d64d5b4966f5300182ad17e1c3b849fc
size 438025495
```

How to download the actual file, just as a file? A zip of the repo does not seem to include the actual file but this pointer. Thus mlhub install does not get the actual file.

Test repository: https://github.com/gjwgit/Tweets-Sentiment-Analysis

```
$ ml install gjwgit/Tweets-Sentiment-Analysis
```

Installs to `~/.mlhub/zynlp/` but `model/best_model_state.bin` contains the above contents.

**Comment by JingjingShii** [comment]
In the forked project,
Go to repo settings
Find "Include Git LFS objects in archives" under the Archives section and check it
Then, the repo will download as .zip
Download will pause for a minute or so before it starts downloading lfs objects. Wait and it should continue.

**Comment by gjwgit** [comment]
Need to be able to do this within mlhub when it downloads the zip file.

The alternative is to include the lfs file within `MLHUB.yaml`.

**Comment by JingjingShii** [comment]
Two ways to download lfs:
1. check 'Include Git LFS objects in archives', then the large file will be included in the repo
2. after the project is downloaded, cd project, git lfs install, git lfs pull --include=best_model_state.bin

The second way might have bandwidth issue because if the user downloads the large file, it will consume the repository owner's allotted bandwidth (Every account has 1GB a month of free bandwidth). Also, the `dependencies` in yaml file doesn't support git now.

**Comment by gjwgit** [comment]
Thanks for investigating. The first solution is the way to go then for lfs files in an archive. A package maintainer needs to be aware of that. Alternatively the package maintainer can store their large pre-built model files somewhere else. The latter is probably the better solution since free GitHub accounts limit downloads to 1GB per month.
