### ISSUE TITLE
Add new KEY functionality for CONFIGURE

### ISSUE THREAD

**Issue by gjwgit** [mlhubber/mlhub#207]
If a package requires a key and location or endpoint or some other "private" information, etc, then CONFIGURE should be requesting that rather than the individual commands having code to obtain and save it.

If an individual command needs the key and there is no private.json in the .mlhub folder, then request the user to run the CONFIGURE command.

This will require MLHUB.yaml to have a new entry to identify that it needs a key and if so CONFIGURE asks for that before all other configurations.

MLHUB.yaml might have:

```
  private : key, location
```

The CONFIGURE command notes this and will prompt for key and location, as in this case, save to the JSON file. The package commands can then load the JSON file, knowing the names of the private entries to obtain. If the file is not present, then the command fails and prints to stderr that the CONFIGURE command should be run first.

**Comment by JingjingShii** [comment]
The format of private row:
`private: Bing Map, key`
`private: Speech, key, location`

**Comment by JingjingShii** [comment]
- [x] Add a new entry (private) in yaml file, CONFIGURE will check private
- [x] If the JSON file exists, running CONFIGURE, a message shows "Do you want to update your key [y/n]?"
- [x] If no JSON file can be found, the command fails, and print the error message
- [x] If the command fails due to the incorrect key, prints to stderr that CONFIGURE needs to run

**Comment by gjwgit** [comment]
Also support:

```
private:
  Azure Speech: key, location
  Google Speech: key
```
